"""Read-only synchronized session analysis for DCMF experiments.

All alignment uses the shared host monotonic timestamps recorded by DCMF.
This is software synchronization, not hardware clock synchronization. Nearest
sample matches retain their time deltas so downstream users can reject loose
matches rather than silently treating them as simultaneous.
"""

from __future__ import annotations

import json
import re
import sqlite3
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd


PRIMARY_CONTROLS = ("roll", "pitch", "yaw", "throttle")


@dataclass(slots=True)
class SessionData:
    """Decoded data streams for one experiment."""

    experiment: dict[str, Any]
    controller: pd.DataFrame
    manual_control: pd.DataFrame
    rc_channels: pd.DataFrame
    servo_outputs: pd.DataFrame
    events: pd.DataFrame
    trials: pd.DataFrame
    sdr: pd.DataFrame
    mavlink_counts: dict[str, int]

    @property
    def experiment_id(self) -> str:
        return str(self.experiment["id"])

    @property
    def start_monotonic_ns(self) -> int:
        return int(self.experiment["started_monotonic_ns"])


@dataclass(slots=True, frozen=True)
class AnalysisResult:
    """Files generated by synchronized analysis."""

    experiment_id: str
    output_directory: Path
    synchronized_csv: Path
    summary_json: Path
    row_count: int


def _connect_read_only(database_path: Path) -> sqlite3.Connection:
    resolved = Path(database_path).resolve()
    connection = sqlite3.connect(
        f"file:{resolved}?mode=ro",
        uri=True,
        timeout=30.0,
    )
    connection.row_factory = sqlite3.Row
    return connection


def _json_object(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    try:
        decoded = json.loads(value or "{}")
    except (TypeError, json.JSONDecodeError):
        return {}
    return decoded if isinstance(decoded, dict) else {}


def _relative_seconds(monotonic_ns: Any, start_ns: int) -> float:
    return (int(monotonic_ns) - start_ns) / 1_000_000_000.0


def _utc_iso(utc_ns: Any) -> str | None:
    if utc_ns is None:
        return None
    return datetime.fromtimestamp(
        int(utc_ns) / 1_000_000_000,
        tz=timezone.utc,
    ).isoformat()


def _empty(columns: Iterable[str]) -> pd.DataFrame:
    return pd.DataFrame(columns=list(columns))


def _load_controller(
    connection: sqlite3.Connection,
    experiment_id: str,
    start_ns: int,
) -> pd.DataFrame:
    rows = connection.execute(
        """
        SELECT monotonic_ns, utc_ns, payload_json
        FROM events
        WHERE experiment_id = ?
          AND source = 'CONTROLLER'
          AND kind = 'SAMPLE'
        ORDER BY monotonic_ns, id
        """,
        (experiment_id,),
    ).fetchall()
    records: list[dict[str, Any]] = []
    for row in rows:
        payload = _json_object(row["payload_json"])
        mapped = payload.get("mapped")
        if not isinstance(mapped, dict):
            mapped = {}
        record: dict[str, Any] = {
            "monotonic_ns": int(row["monotonic_ns"]),
            "utc_ns": int(row["utc_ns"]),
            "time_s": _relative_seconds(row["monotonic_ns"], start_ns),
            "device": str(payload.get("device") or ""),
        }
        for name in PRIMARY_CONTROLS:
            value = mapped.get(name)
            try:
                record[name] = float(value) if value is not None else np.nan
            except (TypeError, ValueError):
                record[name] = np.nan
        records.append(record)
    if not records:
        return _empty(
            ("monotonic_ns", "utc_ns", "time_s", "device", *PRIMARY_CONTROLS)
        )
    return pd.DataFrame.from_records(records)


def _load_mavlink_control_streams(
    connection: sqlite3.Connection,
    experiment_id: str,
    start_ns: int,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, dict[str, int]]:
    count_rows = connection.execute(
        """
        SELECT COALESCE(direction, 'UNKNOWN') AS direction,
               COALESCE(message_name, 'UNKNOWN') AS message_name,
               COUNT(*) AS count
        FROM mavlink_messages
        WHERE experiment_id = ?
        GROUP BY direction, message_name
        """,
        (experiment_id,),
    ).fetchall()
    counts = {
        f"{row['direction']}:{row['message_name']}": int(row["count"])
        for row in count_rows
    }

    rows = connection.execute(
        """
        SELECT monotonic_ns, utc_ns, direction, message_name,
               system_id, component_id, raw_hex, decoded_json
        FROM mavlink_messages
        WHERE experiment_id = ?
          AND message_name IN (
              'MANUAL_CONTROL', 'RC_CHANNELS', 'RC_CHANNELS_RAW',
              'SERVO_OUTPUT_RAW'
          )
        ORDER BY monotonic_ns, id
        """,
        (experiment_id,),
    ).fetchall()

    manual: list[dict[str, Any]] = []
    channels: list[dict[str, Any]] = []
    servos: list[dict[str, Any]] = []
    for row in rows:
        decoded = _json_object(row["decoded_json"])
        common = {
            "monotonic_ns": int(row["monotonic_ns"]),
            "utc_ns": int(row["utc_ns"]),
            "time_s": _relative_seconds(row["monotonic_ns"], start_ns),
            "direction": str(row["direction"] or "UNKNOWN"),
            "system_id": row["system_id"],
            "component_id": row["component_id"],
            "raw_hex": str(row["raw_hex"] or ""),
        }
        if row["message_name"] == "MANUAL_CONTROL":
            item = dict(common)
            for key in ("x", "y", "z", "r", "buttons", "target"):
                item[key] = pd.to_numeric(decoded.get(key), errors="coerce")
            item.update(
                {
                    "pitch": item["x"] / 1000.0,
                    "roll": item["y"] / 1000.0,
                    "throttle": item["z"] / 500.0 - 1.0,
                    "yaw": item["r"] / 1000.0,
                }
            )
            manual.append(item)
            continue

        if row["message_name"] == "SERVO_OUTPUT_RAW":
            item = dict(common)
            item["port"] = pd.to_numeric(decoded.get("port"), errors="coerce")
            for output in range(1, 17):
                numeric = pd.to_numeric(
                    decoded.get(f"servo{output}_raw"), errors="coerce"
                )
                item[f"servo{output}"] = (
                    float(numeric)
                    if numeric is not None
                    and pd.notna(numeric)
                    and float(numeric) > 0
                    else np.nan
                )
            servos.append(item)
            continue

        item = dict(common)
        item["message_name"] = str(row["message_name"])
        for channel in range(1, 19):
            value = decoded.get(f"chan{channel}_raw")
            numeric = pd.to_numeric(value, errors="coerce")
            item[f"ch{channel}"] = (
                float(numeric)
                if numeric is not None
                and pd.notna(numeric)
                and float(numeric) > 0
                else np.nan
            )
        # Project-validated RCMAP: roll=1, pitch=2, throttle=3, yaw=4.
        item["roll"] = (item["ch1"] - 1500.0) / 500.0
        item["pitch"] = (item["ch2"] - 1500.0) / 500.0
        item["throttle"] = (item["ch3"] - 1000.0) / 1000.0 * 2.0 - 1.0
        item["yaw"] = (item["ch4"] - 1500.0) / 500.0
        channels.append(item)

    manual_frame = pd.DataFrame.from_records(manual)
    channel_frame = pd.DataFrame.from_records(channels)
    servo_frame = pd.DataFrame.from_records(servos)
    if manual_frame.empty:
        manual_frame = _empty(
            (
                "monotonic_ns", "utc_ns", "time_s", "direction",
                "system_id", "component_id", "raw_hex", "x", "y", "z",
                "r", "buttons", "target", *PRIMARY_CONTROLS,
            )
        )
    if channel_frame.empty:
        channel_frame = _empty(
            (
                "monotonic_ns", "utc_ns", "time_s", "direction",
                "system_id", "component_id", "raw_hex", "message_name",
                *(f"ch{index}" for index in range(1, 19)), *PRIMARY_CONTROLS,
            )
        )
    if servo_frame.empty:
        servo_frame = _empty(
            (
                "monotonic_ns", "utc_ns", "time_s", "direction",
                "system_id", "component_id", "raw_hex", "port",
                *(f"servo{index}" for index in range(1, 17)),
            )
        )
    return manual_frame, channel_frame, servo_frame, counts


def _load_events_and_trials(
    connection: sqlite3.Connection,
    experiment_id: str,
    start_ns: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    rows = connection.execute(
        """
        SELECT monotonic_ns, utc_ns, source, kind, payload_json
        FROM events
        WHERE experiment_id = ?
        ORDER BY monotonic_ns, id
        """,
        (experiment_id,),
    ).fetchall()
    event_records: list[dict[str, Any]] = []
    pairs: dict[tuple[str, int], dict[str, Any]] = {}
    for row in rows:
        payload = _json_object(row["payload_json"])
        event_records.append(
            {
                "monotonic_ns": int(row["monotonic_ns"]),
                "utc_ns": int(row["utc_ns"]),
                "time_s": _relative_seconds(row["monotonic_ns"], start_ns),
                "source": str(row["source"]),
                "kind": str(row["kind"]),
                "label": str(payload.get("label") or ""),
                "payload": payload,
            }
        )
        if row["source"] != "OPERATOR" or row["kind"] not in {
            "ACTION_START", "ACTION_END"
        }:
            continue
        action = str(payload.get("action") or "").strip()
        try:
            trial_number = int(payload.get("trial_number"))
        except (TypeError, ValueError):
            continue
        if not action or trial_number < 1:
            continue
        pair = pairs.setdefault(
            (action, trial_number),
            {
                "action": action,
                "trial_number": trial_number,
                "start_monotonic_ns": np.nan,
                "end_monotonic_ns": np.nan,
                "automatic_end": False,
            },
        )
        if row["kind"] == "ACTION_START":
            pair["start_monotonic_ns"] = int(row["monotonic_ns"])
        else:
            pair["end_monotonic_ns"] = int(row["monotonic_ns"])
            pair["automatic_end"] = bool(payload.get("automatic", False))

    trial_records: list[dict[str, Any]] = []
    for pair in pairs.values():
        start = pair["start_monotonic_ns"]
        end = pair["end_monotonic_ns"]
        complete = bool(pd.notna(start) and pd.notna(end) and end >= start)
        pair["complete"] = complete
        pair["start_time_s"] = (
            _relative_seconds(start, start_ns) if pd.notna(start) else np.nan
        )
        pair["end_time_s"] = (
            _relative_seconds(end, start_ns) if pd.notna(end) else np.nan
        )
        pair["duration_s"] = (
            (int(end) - int(start)) / 1_000_000_000.0 if complete else np.nan
        )
        trial_records.append(pair)

    events = pd.DataFrame.from_records(event_records)
    trials = pd.DataFrame.from_records(trial_records)
    if events.empty:
        events = _empty(
            ("monotonic_ns", "utc_ns", "time_s", "source", "kind", "label", "payload")
        )
    if trials.empty:
        trials = _empty(
            (
                "action", "trial_number", "start_monotonic_ns",
                "end_monotonic_ns", "automatic_end", "complete",
                "start_time_s", "end_time_s", "duration_s",
            )
        )
    else:
        trials = trials.sort_values(
            ["start_monotonic_ns", "action", "trial_number"],
            na_position="last",
        ).reset_index(drop=True)
    return events, trials


def _load_sdr(
    connection: sqlite3.Connection,
    experiment_id: str,
    start_ns: int,
) -> pd.DataFrame:
    rows = connection.execute(
        """
        SELECT monotonic_ns, utc_ns, record_kind, center_frequency_hz,
               sample_rate_hz, gain_db, power_dbfs, iq_file, metadata_json
        FROM sdr_records
        WHERE experiment_id = ?
        ORDER BY monotonic_ns, id
        """,
        (experiment_id,),
    ).fetchall()
    records = []
    for row in rows:
        records.append(
            {
                "monotonic_ns": int(row["monotonic_ns"]),
                "utc_ns": int(row["utc_ns"]),
                "time_s": _relative_seconds(row["monotonic_ns"], start_ns),
                "record_kind": str(row["record_kind"]),
                "center_frequency_hz": row["center_frequency_hz"],
                "sample_rate_hz": row["sample_rate_hz"],
                "gain_db": row["gain_db"],
                "power_dbfs": row["power_dbfs"],
                "iq_file": str(row["iq_file"] or ""),
                "metadata": _json_object(row["metadata_json"]),
            }
        )
    if not records:
        return _empty(
            (
                "monotonic_ns", "utc_ns", "time_s", "record_kind",
                "center_frequency_hz", "sample_rate_hz", "gain_db",
                "power_dbfs", "iq_file", "metadata",
            )
        )
    return pd.DataFrame.from_records(records)


def load_session(database_path: Path, experiment_id: str) -> SessionData:
    """Load one experiment without modifying SQLite or capture files."""
    connection = _connect_read_only(database_path)
    try:
        row = connection.execute(
            "SELECT * FROM experiments WHERE id = ?",
            (experiment_id,),
        ).fetchone()
        if row is None:
            raise KeyError(f"Experiment not found: {experiment_id}")
        experiment = dict(row)
        experiment["started_utc_iso"] = _utc_iso(experiment["started_utc_ns"])
        experiment["ended_utc_iso"] = _utc_iso(experiment.get("ended_utc_ns"))
        start_ns = int(experiment["started_monotonic_ns"])
        controller = _load_controller(connection, experiment_id, start_ns)
        manual, channels, servos, counts = _load_mavlink_control_streams(
            connection, experiment_id, start_ns
        )
        events, trials = _load_events_and_trials(
            connection, experiment_id, start_ns
        )
        sdr = _load_sdr(connection, experiment_id, start_ns)
        return SessionData(
            experiment=experiment,
            controller=controller,
            manual_control=manual,
            rc_channels=channels,
            servo_outputs=servos,
            events=events,
            trials=trials,
            sdr=sdr,
            mavlink_counts=counts,
        )
    finally:
        connection.close()


def _nearest_join(
    base: pd.DataFrame,
    stream: pd.DataFrame,
    *,
    prefix: str,
    columns: Iterable[str],
    tolerance_ns: int,
) -> pd.DataFrame:
    result = base.copy()
    if stream.empty or result.empty:
        for column in columns:
            result[f"{prefix}_{column}"] = np.nan
        result[f"{prefix}_delta_ms"] = np.nan
        return result

    selected_columns = ["monotonic_ns", *columns]
    right = stream.loc[:, selected_columns].copy()
    right = right.rename(
        columns={
            "monotonic_ns": f"{prefix}_monotonic_ns",
            **{name: f"{prefix}_{name}" for name in columns},
        }
    ).sort_values(f"{prefix}_monotonic_ns")
    result = pd.merge_asof(
        result.sort_values("monotonic_ns"),
        right,
        left_on="monotonic_ns",
        right_on=f"{prefix}_monotonic_ns",
        direction="nearest",
        tolerance=tolerance_ns,
    )
    result[f"{prefix}_delta_ms"] = (
        result[f"{prefix}_monotonic_ns"] - result["monotonic_ns"]
    ) / 1_000_000.0
    return result.drop(columns=[f"{prefix}_monotonic_ns"])


def synchronize_session(
    session: SessionData,
    *,
    tolerance_ms: float = 250.0,
) -> pd.DataFrame:
    """Align controls, TX commands, returned RC channels, and labels."""
    tolerance_ns = int(max(0.0, tolerance_ms) * 1_000_000.0)
    synchronized = session.controller.copy()
    synchronized = _nearest_join(
        synchronized,
        session.manual_control,
        prefix="manual",
        columns=("direction", "x", "y", "z", "r", *PRIMARY_CONTROLS),
        tolerance_ns=tolerance_ns,
    )
    synchronized = _nearest_join(
        synchronized,
        session.rc_channels,
        prefix="rc",
        columns=("direction", "ch1", "ch2", "ch3", "ch4", *PRIMARY_CONTROLS),
        tolerance_ns=tolerance_ns,
    )
    synchronized = _nearest_join(
        synchronized,
        session.servo_outputs,
        prefix="servo",
        columns=tuple(f"servo{index}" for index in range(1, 17)),
        tolerance_ns=tolerance_ns,
    )
    synchronized["guided_action"] = ""
    synchronized["trial_number"] = pd.Series(
        pd.NA, index=synchronized.index, dtype="Int64"
    )
    for trial in session.trials.to_dict(orient="records"):
        if not trial.get("complete"):
            continue
        mask = (
            (synchronized["monotonic_ns"] >= int(trial["start_monotonic_ns"]))
            & (synchronized["monotonic_ns"] <= int(trial["end_monotonic_ns"]))
        )
        synchronized.loc[mask, "guided_action"] = str(trial["action"])
        synchronized.loc[mask, "trial_number"] = int(trial["trial_number"])
    return synchronized.reset_index(drop=True)


def _correlations(frame: pd.DataFrame) -> dict[str, float | None]:
    pairs = {
        "controller_vs_manual_roll": ("roll", "manual_roll"),
        "controller_vs_manual_pitch": ("pitch", "manual_pitch"),
        "controller_vs_manual_yaw": ("yaw", "manual_yaw"),
        "controller_vs_manual_throttle": ("throttle", "manual_throttle"),
        "controller_vs_rc_roll": ("roll", "rc_roll"),
        "controller_vs_rc_pitch": ("pitch", "rc_pitch"),
        "controller_vs_rc_yaw": ("yaw", "rc_yaw"),
        "controller_vs_rc_throttle": ("throttle", "rc_throttle"),
    }
    result: dict[str, float | None] = {}
    for label, (left, right) in pairs.items():
        if left not in frame or right not in frame:
            result[label] = None
            continue
        valid = frame[[left, right]].dropna()
        if len(valid) < 3 or valid[left].nunique() < 2 or valid[right].nunique() < 2:
            result[label] = None
            continue
        result[label] = float(valid[left].corr(valid[right]))
    return result


def build_analysis_summary(
    session: SessionData,
    synchronized: pd.DataFrame,
    *,
    tolerance_ms: float,
) -> dict[str, Any]:
    """Create a serializable high-level analysis report."""
    complete_trials = (
        int(session.trials["complete"].fillna(False).sum())
        if "complete" in session.trials
        else 0
    )
    delta_summary: dict[str, dict[str, float | int | None]] = {}
    for name in ("manual_delta_ms", "rc_delta_ms", "servo_delta_ms"):
        values = pd.to_numeric(synchronized.get(name), errors="coerce").dropna()
        delta_summary[name] = {
            "matched_rows": int(len(values)),
            "median_absolute_ms": (
                float(values.abs().median()) if len(values) else None
            ),
            "max_absolute_ms": (
                float(values.abs().max()) if len(values) else None
            ),
        }

    return {
        "experiment": session.experiment,
        "synchronization": {
            "clock": "shared host monotonic timestamps",
            "hardware_synchronized": False,
            "method": "nearest timestamp match",
            "tolerance_ms": tolerance_ms,
            "match_delta_convention": "stream timestamp minus controller timestamp",
        },
        "counts": {
            "controller_samples": int(len(session.controller)),
            "manual_control_messages": int(len(session.manual_control)),
            "rc_channel_messages": int(len(session.rc_channels)),
            "servo_output_messages": int(len(session.servo_outputs)),
            "events": int(len(session.events)),
            "sdr_records": int(len(session.sdr)),
            "guided_trials": int(len(session.trials)),
            "complete_guided_trials": complete_trials,
            "synchronized_rows": int(len(synchronized)),
        },
        "mavlink_counts": session.mavlink_counts,
        "alignment": delta_summary,
        "correlations": _correlations(synchronized),
        "limitations": [
            "Alignment is host-software timestamp based; it is not hardware clock synchronization.",
            "RC normalization assumes the project-validated RCMAP roll=1, pitch=2, throttle=3, yaw=4.",
            "SDR center-frequency capture may observe only part of a frequency-hopping telemetry link.",
            "Correlation is descriptive and does not prove causality or protocol semantics.",
        ],
    }


def _safe_name(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_-]+", "-", value.strip()).strip("-_")
    return cleaned[:80] or "experiment"


def analyze_experiment(
    database_path: Path,
    experiment_id: str,
    output_root: Path = Path("analysis"),
    *,
    tolerance_ms: float = 250.0,
) -> AnalysisResult:
    """Generate synchronized CSV and JSON summary for one experiment."""
    session = load_session(database_path, experiment_id)
    synchronized = synchronize_session(session, tolerance_ms=tolerance_ms)
    folder = (
        f"{_safe_name(str(session.experiment.get('name') or 'experiment'))}_"
        f"{experiment_id[:8]}"
    )
    output_directory = Path(output_root) / folder
    output_directory.mkdir(parents=True, exist_ok=True)
    synchronized_csv = output_directory / "synchronized_samples.csv"
    summary_json = output_directory / "analysis_summary.json"
    synchronized.to_csv(synchronized_csv, index=False)
    summary = build_analysis_summary(
        session, synchronized, tolerance_ms=tolerance_ms
    )
    summary_json.write_text(
        json.dumps(summary, indent=2, sort_keys=True, default=str) + "\n",
        encoding="utf-8",
    )
    return AnalysisResult(
        experiment_id=experiment_id,
        output_directory=output_directory,
        synchronized_csv=synchronized_csv,
        summary_json=summary_json,
        row_count=len(synchronized),
    )
